swagger: '2.0'
tags:
- name: websites
  description: websites API

paths:
# [GET] websites
  /websites:
    get:
      tags:
      - websites
      summary: Find All Websites
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] websites
    post:
      tags:
      - websites
      summary: Add Website
      parameters:
      - name: body
        in: body
        description: website Data
        required: true
        schema:
          $ref: '#/definitions/websites'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] websites/id
  /websites/{id}:
    get:
      tags:
      - websites
      summary: Find Website By Id
      parameters:
      - name: id
        in: path
        description: Website Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] websites/id
    put:
      tags:
      - websites
      summary: Update Website By Id
      parameters:
      - name: id
        in: path
        description: website Id
        required: true
        type: integer
      - name: body
        in: body
        description: website Data
        required: true
        schema:
          $ref: '#/definitions/websites'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] websites/id
    delete:
      tags:
      - websites
      summary: Delete Website By Id
      parameters:
      - name: id
        in: path
        description: website Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  websites:
    type: object
    required:
        - url
        - name
    properties:
      id:
        type: integer
        description: website Id
      name:
        type: string
        description: website Name
      url:
        type: string
        description: website Url
      is_active:
        type: boolean
schemes:
 - https
 - http
